## Swiggy India Exploratory Data Analysis

This is an EDA project about a food delivery app named Swiggy.
Data is taken from kaggle to keep EDA practice as real as possible.

1. We will import all the required libraries for the analysis.

In [1]:
import numpy as np 
import pandas as pd

2. Importing dataset from csv file and print first 5 records using head function in pandas to analyse the data and clean it accordingly.

In [2]:
data = pd.read_csv(r"..\data\raw\swiggy.csv")
data.head

<bound method NDFrame.head of             id                      name      city rating     rating_count  \
0       567335            AB FOODS POINT    Abohar     --  Too Few Ratings
1       531342         Janta Sweet House    Abohar    4.4      50+ ratings
2       158203         theka coffee desi    Abohar    3.8     100+ ratings
3       187912                 Singh Hut    Abohar    3.7      20+ ratings
4       543530             GRILL MASTERS    Abohar     --  Too Few Ratings
...        ...                       ...       ...    ...              ...
148536  553122          The Food Delight  Yavatmal     --  Too Few Ratings
148537  562647  MAITRI FOODS & BEVERAGES  Yavatmal     --  Too Few Ratings
148538  559435           Cafe Bella Ciao  Yavatmal     --  Too Few Ratings
148539  418989               GRILL ZILLA  Yavatmal     --  Too Few Ratings
148540  447770            Lazeez kitchen  Yavatmal     --  Too Few Ratings

         cost                     cuisine          lic_no  \
0       ₹ 200            Beverages,Pizzas  22122652000138
1       ₹ 200               Sweets,Bakery  12117201000112
2       ₹ 100                   Beverages  22121652000190
3       ₹ 250            Fast Food,Indian  22119652000167
4       ₹ 250  Italian-American,Fast Food  12122201000053
...       ...                         ...             ...
148536  ₹ 200            Fast Food,Snacks  21522053000452
148537  ₹ 300                      Pizzas         license
148538  ₹ 300            Fast Food,Snacks  21522251000378
148539  ₹ 250                 Continental  21521251000241
148540  ₹ 200                      Pizzas  21521251000634

                                                     link  \
0       https://www.swiggy.com/restaurants/ab-foods-po...
1       https://www.swiggy.com/restaurants/janta-sweet...
2       https://www.swiggy.com/restaurants/theka-coffe...
3       https://www.swiggy.com/restaurants/singh-hut-n...
4       https://www.swiggy.com/restaurants/grill-maste...
...                                                   ...
148536  https://www.swiggy.com/restaurants/the-food-de...
148537  https://www.swiggy.com/restaurants/maitri-food...
148538  https://www.swiggy.com/restaurants/cafe-bella-...
148539  https://www.swiggy.com/restaurants/grill-zilla...
148540  https://www.swiggy.com/restaurants/lazeez-kitc...

                                                  address              menu
0       AB FOODS POINT, NEAR RISHI NARANG DENTAL CLINI...  Menu/567335.json
1       Janta Sweet House, Bazar No.9, Circullar Road,...  Menu/531342.json
2              theka coffee desi, sahtiya sadan road city  Menu/158203.json
3         Singh Hut, CIRCULAR ROAD NEAR NEHRU PARK ABOHAR  Menu/187912.json
4       GRILL MASTERS, ADA Heights, Abohar - Hanumanga...  Menu/543530.json
...                                                   ...               ...
148536  The Food Delight, 94MC+X35, New Singhania Naga...  Menu/553122.json
148537  MAITRI FOODS & BEVERAGES, POLIC MITRYA SOCIETY...  Menu/562647.json
148538  Cafe Bella Ciao, SHOP NO 2 NEMANI MARKET SBI S...  Menu/559435.json
148539  GRILL ZILLA, SHO NO 2/6, POSTEL GROUND CHOWPAT...  Menu/418989.json
148540  Lazeez kitchen, 94G3+2RR, Wadgaon, Yavatmal, M...  Menu/447770.json

[148541 rows x 11 columns]>

After analysing the data few functions are made to clean the data in the above dataset

3. We have created a seprate file of functions to clean the data in data_cleaning.py in src directory. This will help us to increase readability of the code in this notebook.
Now, we will add path of directory to the system for access to functions.
List of functions created in data_cleaning.py are:- 
    1. clean_column_names
    2. clean_rating_column
    3. clean_rating_count

In [3]:
import sys
sys.path.append('../src')

4. Apply created functions to the data.

In [4]:
from data_cleaning import clean_column_names
from data_cleaning import clean_rating_column
from data_cleaning import clean_rating_count
clean_column_names(data)
clean_rating_column(data)
clean_rating_count(data)

,id,name,city,rating,rating_count,cost,cuisine,lic_no,link,address,menu
0,567335,AB FOODS POINT,Abohar,NaN,NaN,₹ 200,"Beverages,Pizzas",22122652000138,https://www.swiggy.com/restaurants/ab-foods-po...,"AB FOODS POINT, NEAR RISHI NARANG DENTAL CLINI...",Menu/567335.json
1,531342,Janta Sweet House,Abohar,4.4,50.0,₹ 200,"Sweets,Bakery",12117201000112,https://www.swiggy.com/restaurants/janta-sweet...,"Janta Sweet House, Bazar No.9, Circullar Road,...",Menu/531342.json
2,158203,theka coffee desi,Abohar,3.8,100.0,₹ 100,Beverages,22121652000190,https://www.swiggy.com/restaurants/theka-coffe...,"theka coffee desi, sahtiya sadan road city",Menu/158203.json
3,187912,Singh Hut,Abohar,3.7,20.0,₹ 250,"Fast Food,Indian",22119652000167,https://www.swiggy.com/restaurants/singh-hut-n...,"Singh Hut, CIRCULAR ROAD NEAR NEHRU PARK ABOHAR",Menu/187912.json
4,543530,GRILL MASTERS,Abohar,NaN,NaN,₹ 250,"Italian-American,Fast Food",12122201000053,https://www.swiggy.com/restaurants/grill-maste...,"GRILL MASTERS, ADA Heights, Abohar - Hanumanga...",Menu/543530.json
...,...,...,...,...,...,...,...,...,...,...,...
148536,553122,The Food Delight,Yavatmal,NaN,NaN,₹ 200,"Fast Food,Snacks",21522053000452,https://www.swiggy.com/restaurants/the-food-de...,"The Food Delight, 94MC+X35, New Singhania Naga...",Menu/553122.json
148537,562647,MAITRI FOODS & BEVERAGES,Yavatmal,NaN,NaN,₹ 300,Pizzas,license,https://www.swiggy.com/restaurants/maitri-food...,"MAITRI FOODS & BEVERAGES, POLIC MITRYA SOCIETY...",Menu/562647.json
148538,559435,Cafe Bella Ciao,Yavatmal,NaN,NaN,₹ 300,"Fast Food,Snacks",21522251000378,https://www.swiggy.com/restaurants/cafe-bella-...,"Cafe Bella Ciao, SHOP NO 2 NEMANI MARKET SBI S...",Menu/559435.json
148539,418989,GRILL ZILLA,Yavatmal,NaN,NaN,₹ 250,Continental,21521251000241,https://www.swiggy.com/restaurants/grill-zilla...,"GRILL ZILLA, SHO NO 2/6, POSTEL GROUND CHOWPAT...",Menu/418989.json
148540,447770,Lazeez kitchen,Yavatmal,NaN,NaN,₹ 200,Pizzas,21521251000634,https://www.swiggy.com/restaurants/lazeez-kitc...,"Lazeez kitchen, 94G3+2RR, Wadgaon, Yavatmal, M...",Menu/447770.json

5. Removed unwanted features to reduce complexity of data

In [5]:
data = data.drop(columns=["link", "address", "menu","lic_no"])
data.head()

,id,name,city,rating,rating_count,cost,cuisine
0,567335,AB FOODS POINT,Abohar,NaN,NaN,₹ 200,"Beverages,Pizzas"
1,531342,Janta Sweet House,Abohar,4.4,50.0,₹ 200,"Sweets,Bakery"
2,158203,theka coffee desi,Abohar,3.8,100.0,₹ 100,Beverages
3,187912,Singh Hut,Abohar,3.7,20.0,₹ 250,"Fast Food,Indian"
4,543530,GRILL MASTERS,Abohar,NaN,NaN,₹ 250,"Italian-American,Fast Food"

6. Filling nan values of rating and rating_count to 0

In [6]:
data["rating"] = data["rating"].fillna(0)
data["rating_count"] = data["rating_count"].fillna(0)
data.head()

,id,name,city,rating,rating_count,cost,cuisine
0,567335,AB FOODS POINT,Abohar,0.0,0.0,₹ 200,"Beverages,Pizzas"
1,531342,Janta Sweet House,Abohar,4.4,50.0,₹ 200,"Sweets,Bakery"
2,158203,theka coffee desi,Abohar,3.8,100.0,₹ 100,Beverages
3,187912,Singh Hut,Abohar,3.7,20.0,₹ 250,"Fast Food,Indian"
4,543530,GRILL MASTERS,Abohar,0.0,0.0,₹ 250,"Italian-American,Fast Food"

7. Now the data is cleaned fully so we will export the data and visualize it to extact usefull insights form the data.

In [ ]:
# data.to_csv('../data/processed/swiggy_cleaned.csv', index=False)

8. After the data is cleaned from our side lets check summary of the dataset.
This will help to check weather the data is cleaned sucessfully without any problem left.

In [8]:
# data.info()
data.describe()

                  id         rating   rating_count
count  148541.000000  148541.000000  148541.000000
mean   363466.378912       1.610866      35.608680
std    167890.977174       1.940654      88.172843
min       211.000000       0.000000       0.000000
25%    233320.000000       0.000000       0.000000
50%    412628.000000       0.000000       0.000000
75%    502223.000000       3.800000      20.000000
max    581031.000000       5.000000     500.000000

9. Here we can see that the cost column is not showing its statistical summary.
    Problem with it is, that cost column is not in int or float it is considered as string as showen with data.info method.

In [9]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 148541 entries, 0 to 148540
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            148541 non-null  int64
 1   name          148455 non-null  str
 2   city          148541 non-null  str
 3   rating        148541 non-null  float64
 4   rating_count  148541 non-null  float64
 5   cost          148410 non-null  str
 6   cuisine       148442 non-null  str
dtypes: float64(2), int64(1), str(4)
memory usage: 7.9 MB

10. To handle this we will need to convert str to int or float.
    we will create a function in our data_cleaning.py

In [10]:
#Importing the function and using it 
from data_cleaning import cost_str_to_float
cost_str_to_float(data)

,id,name,city,rating,rating_count,cost,cuisine
0,567335,AB FOODS POINT,Abohar,0.0,0.0,200.0,"Beverages,Pizzas"
1,531342,Janta Sweet House,Abohar,4.4,50.0,200.0,"Sweets,Bakery"
2,158203,theka coffee desi,Abohar,3.8,100.0,100.0,Beverages
3,187912,Singh Hut,Abohar,3.7,20.0,250.0,"Fast Food,Indian"
4,543530,GRILL MASTERS,Abohar,0.0,0.0,250.0,"Italian-American,Fast Food"
...,...,...,...,...,...,...,...
148536,553122,The Food Delight,Yavatmal,0.0,0.0,200.0,"Fast Food,Snacks"
148537,562647,MAITRI FOODS & BEVERAGES,Yavatmal,0.0,0.0,300.0,Pizzas
148538,559435,Cafe Bella Ciao,Yavatmal,0.0,0.0,300.0,"Fast Food,Snacks"
148539,418989,GRILL ZILLA,Yavatmal,0.0,0.0,250.0,Continental
148540,447770,Lazeez kitchen,Yavatmal,0.0,0.0,200.0,Pizzas

In [11]:
data.describe()

                  id         rating   rating_count           cost
count  148541.000000  148541.000000  148541.000000  148410.000000
mean   363466.378912       1.610866      35.608680     287.600714
std    167890.977174       1.940654      88.172843     796.730688
min       211.000000       0.000000       0.000000       1.000000
25%    233320.000000       0.000000       0.000000     200.000000
50%    412628.000000       0.000000       0.000000     250.000000
75%    502223.000000       3.800000      20.000000     300.000000
max    581031.000000       5.000000     500.000000  300350.000000

11. Now the problem is that cost count is less then the actual count, means cost contains null values.

In [15]:
data['cost']=data['cost'].fillna(data['cost'].mean)
data.describe()

                  id         rating   rating_count
count  148541.000000  148541.000000  148541.000000
mean   363466.378912       1.610866      35.608680
std    167890.977174       1.940654      88.172843
min       211.000000       0.000000       0.000000
25%    233320.000000       0.000000       0.000000
50%    412628.000000       0.000000       0.000000
75%    502223.000000       3.800000      20.000000
max    581031.000000       5.000000     500.000000

12. Export the file

In [16]:
data.to_csv('../data/processed/swiggy_cleaned.csv', index=False)